site_name: NLP Chadian
site_url: https://mydomain.org/mysite
site_description: NLP Chadian est un projet portant sur les langues locales du Tchad. Il a pour objectif de promouvoir les langues locales du Tchad en les rendant accessibles à tous.
repo_url: https://github.com/abdelazizharane/Corpus-Chadian-Languages
theme:
  name: material
  custom_dir: overrides
  icon:
    logo: fontawesome/brands/buysellads #:simple-htop: :simple-htmx: 
#  logo: assets/logoNLPChadianlanguages.png
    favicon: fontawesome/brands/buysellads # Ajout de favicon
    touchicon: fontawesome/brands/buysellads # Ajout de touchicon
    repo: fontawesome/brands/github # Ajout de repo
  ######### AJout de footer
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.expand
    - mavigation.expansion
    - navigation.sections
    - search.highlight
    - navigation.indexes
    - navigation.prev_next
    - navigation.top
    - navigation.bottom
    - navigation.page_number
    - navigation.scroll_top
  nav:
    - Accueil: index.md
    - Blog: 
        - Articles récents: blog/index.md
        - Tous les articles: blog/posts/index.md
    - Documentation:
        - Introduction: docs/index.md
        - Projet NLP pour les Langues Tchadiennes: docs/nlp_chad.md
    - À propos: about.md

  palette: # Options de couleurs: 'default', 'slate', 'indigo', 'red', 'green', 'teal', 'cyan', 'light blue', 'blue', 'purple', 'deep purple', 'pink', 'blue grey', 'brown', 'grey'
    - scheme: slate# Dark Mode
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: blue grey
      accent: deep purple
    - scheme: default  # Light Mode
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: teal
      accent: deep orange

plugins:
  - search
  - blog:
      summary: true
      authors_profiles: true      
      authors_file: "{blog}/.authors.yml"

###### Ajout et utilisation de plus de 1000 émojis et icônes
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
# Ajout d'ajustement des blogs de code dans les articles
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # Ajout des ongles la table des matières
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
    #Les avertissements (ou rappels)
  - admonition
  - pymdownx.details
  - pymdownx.superfences

# Ajout des réseaux sociaux
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/abdelazizharane 
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/abdel-aziz-harane
      
# Ajout de copyright
copyright: Copyright &copy; 2025 Abdel-aziz Harane