authors:
  abdelazizharane: # Author slug
    name: Abdel-aziz Harane Abounounou        # Author name
    description: AI Engineer & Founder Chad AI Network # Author description
    avatar: https://github.com/abdelazizharane/docnlpChad/blob/master/docs/assets/AbdelH.png        # Author avatar
    #slug: url           # Author profile slug
    url: http://abdelazizharane.github.io/datavibes  # Author website URL
    
    mahamat: # Author slug
      name: Mahamat Ahmat        # Author name
      description: Member of project # Author description
      avatar: ../docs/assets/AbdelH.png        # Author avatar
      #slug: url           # Author profile slug
      url: http://abdelazizharane.github.io/datavibes  # Author website URL  